namespace Domain
{
    public enum PersonalityArchtype
    {
        Architect = 0,
        Autocrat = 1,
        BomVivant = 2,
        Bravo = 3,
        Capitalist = 4,
        Caregiver = 5,
        Celebrant = 6,
        Chameleon = 7,
        Child = 8,
        Competitor = 9,
        Conformist = 10,
        Conniver = 11,
        CreepShow = 12,
        Curmudgeon = 13,
        Dabbler = 14,
        Deviant = 15,
        Director = 16,
        Enigma = 17,
        EyeOfTheStorm = 18,
        Fanatic = 19,
        Gallant = 20,
        Guru = 21,
        Idealist = 22,
        Judge = 23,
        Loner = 24,
        Martyr = 25,
        Masochist = 26,
        Monster = 27,
        Pedagogue = 28,
        Penitent = 29,
        Perfectionist = 30,
        Rebel = 31,
        Rogue = 32,
        Sadist = 33,
        Scientist = 34,
        Sociopath = 35,
        Soldier = 36,
        Survivor = 37,
        ThrillSeeker = 38,
        Traditionalist = 39,
        Trickster = 40,
        Visionary = 41,
    }
}
